### PR TITLE
015: Delete server connection step in bundle sysatt110 and add testConnection function in bundle util

### PR DESCRIPTION
**Pull request by Romain-SHT**

### CODE REVIEW

**Comment by bjhargrave** [comment]
Why did you revert the PR from Tim?

**Comment by Romain-SHT** [comment]
Operating error, I restore Tim's updates

**Comment by Romain-SHT** [comment]
Or maybe Tim could send a new PR ?

**Comment by bjhargrave** [comment]
Since you merged the PR and then reverted the commit, you should revert the
revert.

On Wed, May 25, 2016 at 9:45 AM Romain-SHT <notifications@github.com> wrote:

> Or maybe Tim could send a new PR ?
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/osgi/osgi.security-tests/pull/17#issuecomment-221580471>
>
-- 
-- 
BJ

**Pull request merged**
